### ISSUE TITLE
No issue.

### ISSUE THREAD

**Issue by Vincz** [bydavy/EFI-ASRock-Z390-Phantom-Gaming#2]
Hey man. No issue here, just wanted to thank you for sharing.
I have a similar setup, it helped me a lot and saved me a lot of time !
I just received the BCM94352Z and I'm gonna try the switch :)
If you add a donate link, I'll pay you a couple of beer !
Thanks again!

**Comment by bydavy** [comment]
Thanks a lot for dropping a message.
