### ISSUE TITLE
some problems with audio

### ISSUE THREAD

**Issue by kaikidd** [bydavy/EFI-ASRock-Z390-Phantom-Gaming#3]
I have the same platform as your. 
But I can't use the audio  output in monitor by HDMI, also the inner output line as green port can't work either.
If I throw the kext named VoodooHDA.kext from the kexts folder. All the audio is ok.
But I want the VoodooHDA.kext fix the audio names in audio bar, which can make me recognize the port I use.
Do you have this problem? 
How can I fix the problem? 
Thank you!

**Comment by bydavy** [comment]
I would recommend to install VoodooHDA.pkg, as it install the system pref panel you might have slightly more control. 
https://sourceforge.net/projects/voodoohda/

**Comment by bydavy** [comment]
Since I got not update. I am closing this issue.
