### ISSUE TITLE
Does FileVault 2 work with this setup?

### ISSUE THREAD

**Issue by DaveFlowberries** [bydavy/EFI-ASRock-Z390-Phantom-Gaming#4]
Just curious if you tested it, since I tried before and it locked me out of the system.

**Comment by bydavy** [comment]
I have not tried yet. I will keep this in my bucket list.

Another solution, would be to use the encryption technology that comes with Samsung 970 EVO, it is called opal. You will not even see the regular disk partitions unless you unlock the disk. It's all supported on hardware at native speed. It happens before clover and OS loading.

**Comment by DaveFlowberries** [comment]
Thanks, little hesitant to go with hardware based encryption after discovering how badly it's implemented:

https://www.zdnet.com/article/flaws-in-self-encrypting-ssds-let-attackers-bypass-disk-encryption/

Guess I will just test Filevault myself once I got my system back up and running, then report back. First time i tried this it froze the system and i had to reformat, will try to follow a tutorial this time.

**Comment by DaveFlowberries** [comment]
Just updating this. It works, you just need the correct drivers in drivers64UEFI. 

They can be found in the EFI/CLOVER/drivers-Off/drivers64UEFI/FileVault2 
Located here  https://sourceforge.net/projects/cloverefiboot/files/Bootable_ISO/

Make sure you don't have "preboot" excluded from "GUI" "Hide Volume" in clover config, otherwise you won't see the new FileVault boot option.
