### ISSUE TITLE
Sensors not working

### ISSUE THREAD

**Issue by DaveFlowberries** [bydavy/EFI-ASRock-Z390-Phantom-Gaming#6]
Any idea how to fix it? The CPU temps are not being properly monitored, thus, fans are not ramping up when testing max load, and temps are much higher as a result.

**Comment by bydavy** [comment]
I did not added kexts for sensors but they are only for user facing data. Have you plugged the fan on the correct pin? This is regulated by the motherboard and the operating system doesn't need to be involved.
